// User Actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const DELETE_USER = "DELETE_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const LOAD_USER = "LOAD_USER";
export const ERROR_USER = "ERROR_USER";
export const CURRENT_USER = "CURRENT_USER";
export const UPDATE_USER = "UPDATE_USER";

// Category Actions
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const ERROR_CATEGORY = "ERROR_CATEGORY";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

// Resource Actions
export const ADD_RESOURCE = "ADD_RESOURCE";
export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const LOAD_RESOURCES = "LOAD_RESOURCES";
export const ERROR_RESOURCE = "ERROR_RESOURCE";
export const GET_RESOURCE_BY_ID = "GET_RESOURCE_BY_ID";
export const GET_ALL_RESOURCES = "GET_ALL_RESOURCES";
